### ISSUE TITLE
web based viewer for the queries that happen (to see them grouped per request/loop)

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [jmcarp/nplusone#1]
it tends to be helpfull to be able to view queries in groups/lists per request
when debugging general sql problems

**Comment by danpalmer** [comment]
Perhaps a Django Debug Toolbar panel would be appropriate for this?

**Comment by RonnyPfannschmidt** [comment]
im not using django

**Comment by RonnyPfannschmidt** [comment]
closing to get if off my plate on github
