### ISSUE TITLE
[django] Do not generate warning for (un)needed `prefetch_related` on `get`

### ISSUE THREAD

**Issue by twidi** [jmcarp/nplusone#10]
Hello.

I love the idea of this app. Wanted this/to create it for years. So, thank you.

One thing that annoy me a little is this: in the test `test_many_to_one_reverse`, `nplusone` generates a warning when selecting addresses for a user.

But I don't think it should, as doing a `prefetch_related` here won't change anything: we'll still have two queries, one to get the first user, and one to get the addresses (instantly if we use `prefetch_related`, and only when asking for addreses when not)

Sadly this prevents me to really use this lib because it can happens a lot as there is no optimization to do here, so nobody does a `prefetch_related` for a `get` (or `.first()` too?).
Think of edit forms, detail views...

The only way to change this would be to monkey patch the `get` method, to not take the current queryset into action for missing `prefetch_related` (but still do for missing `select_related`).

**Comment by twidi** [comment]
Checking in the code, I think that not only `get`, but generally `__getitem__`. It will do the `prefetch_related` queries each time we do `my_queryset[index]`

I still don't know in your code how  to ignore relations that are not FK or OneToOne  for `__getitem__`

**Comment by jmcarp** [comment]
Good point. One option might be to ignore queries that return a single result, like `queryset.first()` or `queryset[2]`. That's how bullet tries to handle this problem: https://github.com/flyerhzm/bullet/blob/master/lib/bullet/active_record42.rb. We could monkeypatch `queryset.__iter__`, and only warn on lazy loads when >1 objects were returned in the original load.

Does that make sense? I can try it out soon.

**Comment by twidi** [comment]
`first` and `get` both call `queryset[0]` so yes it's the same as `queryset[2]`, it's why I talked about `__getitem__`. By the way we should not totally ignore queries, as FK (or One2One) that are not included with `select_related` should still emit a warning.

**Comment by twidi** [comment]
I really tried to do something but I didn't succeed to have a full vision of what the code is doing :)

**Comment by jmcarp** [comment]
I started working on this in #11.

**Comment by twidi** [comment]
I just saw you merged your work. I'll try as soon as Tuesday ! Thanks a lot!

**Comment by twidi** [comment]
It seems ok, I close the issue :)

Fixed in #11
