### ISSUE TITLE
Ignore queries retrieving no data

### ISSUE THREAD

**Issue by twidi** [jmcarp/nplusone#13]
If I use a relation (prefetched via `prefetch_related` in django for example) in a loop but the query returned no data, `nplusone` think that it's a "eager load'

It should only think this way if actual data is returned, because this causes a lot of false positive :(

**Comment by jmcarp** [comment]
Could you give an example of the kind of query that turns up this problem? Or, even better, write a failing test? I'll try to get this fixed quickly once I understand exactly what's going on.

**Comment by twidi** [comment]
Actually there is a lot mode to do :)

I currently use your lib on a quite big django application and I discovered a lot of little and big problems.

I update the `ext/django/patch.py` file on the go, and when done, I'll try to split in little pull requests (and leave some parts to be rewritten because I did some ugly hacks :) )

**Comment by jmcarp** [comment]
Thanks for your help!

**Comment by twidi** [comment]
I think in two days I spent more time managing problems with this lib than with the application I cork for... but it's not a problem at all, It help us, and will help other after that.

PS: I think I'm starting to understand how the whole thing is currently working :D

**Comment by jmcarp** [comment]
@twidi: any updates on this? I'm looking forward to merging your pull requests and fixing bugs that you found. No problem if you don't have time to split up work into small pull requests.

**Comment by jmcarp** [comment]
I recently ran into this issue myself, and now I understand what you were saying--sorry I didn't figure this out earlier. Anyway, this should be improved as of 0.7.0. See #14 for updates. I'm going to close this for now, but please reopen or file a new issue if you continue to see problems.
